document.write('<br><br>',

'<H2><p style="color:white;"><b> - EJEMPLOS en C</b> </p></H2>',
'<br>',
'<br>',
'<a href="arduino_Comprobacion_protoboard.html"> - Comprobacion conexiones protoboard y coche fantastico</a> ',
'<br> ',
'<br> ',
'<a href="arduino_tiempo.html"> - Contador de minutos y segundos</a> ',
'<br>',
'<br>',
'<a href="arduino_ilumina.html"> - Iluminacion  regulada con LDR</a> ',
'<br>',
'<br> ',
'<a href="arduino_preguntas.html"> - Preguntas</a> ',
'<br>',
'<br>',
'<a href="arduino_telerruptor.html"> - Telerruptor</a> ',
'<br>',
'<br>',
'<a href="arduino_pulsacionLargaCorta.html"> - Pulsacion Larga Corta</a> ',
'<br>',
'<br>',
'<a href="arduino_contador.html"> - Encendido de led con contador de pulsos</a> ',
'<br>',
'<br>',
'<a href="arduino_pulsosubida.html"> - Flanco de subida.</a> ',
'<br>',
'<br>',
'<a href="arduino_Impresion_segun_duracion_pulso.html"> - Bit Pulso que se repite ciclicamente</a> ',
'<br>',
'<br>',
'<a href="arduino_IR.html"> - Mando de IR</a> ',
'<br>',
'<br>',
'<a href="arduino_IRmasPulsador.html"> - Encendido de un led por pulsador o IR</a> ',
'<br>',
'<br>',
'<a href="arduino_persiana.html"> - Persiana</a> ',
'<br>',
'<br>',
'<br>');