document.write(
'<ul class="menu">',
'  <li> <a href="../index.html" >Inicio</a></li>',
'  <li> <a href="https://cifpmedinadelcampo.es/iea/" >CIFP Electricidad</a></li>',
'  <li> <a href="../webInterior/Interior.html" >vivienda</a>',
'      <ul>',
'          <li> <a href="../webInterior/Interior.html" >Interior</a>',  			
'     	   </li> ',
'         <li> <a href="../webDomotica/Domotica.html">Domotica</a>',   			 
'  		  </li>',
'      </ul> ',
'  </li>',
'  <li> <a href="../webAutomatismos/index.html" >Automatismos</a>',
'      <ul>',
'          <li> <a href="../webAutomatismos/cableados.html">Cableados</a>',
'     			 <ul>',
'          			<li> <a href="../webAutomatismos/cableados.html">Control de Motores</a></li>',
'          			<li> <a href="../webAutomatismos/cableados_analizar.html">Ejercicios A.Cableados</a></li>',
'     			</ul> ',
'     	   </li> ',

'         <li> <a href="../webAutomatismos/programados.html">Programados</a>',
'     			 <ul>',
'          			<li> <a href="../webAutomatismos/programados.html">S7-200</a>',
'          			<li> <a href="../webAutomatismos/LOGO.html">LOGO</a>',
'          			<li> <a href="../webAutomatismos/tiaportal.html">TIA-PORTAL</a>',
'     			</ul> ',
'  		  </li>',
'      </ul> ',
'  </li>',

'  <li> <a href="#" >Motor/Variador</a>',
'      <ul>',
'  		   <li> <a href="../webMotores/motores.html" >Motores</a>',
'          <li> <a href="../webMotores/Variadores.html">Variadores</a>',
'          <li> <a href="../webMotores/variadores_practicas.html">Practicas Variadores</a>',
'      </ul> ',
'  </li>',
'  <li> <a href="../webRenovables/Renovables.html" >Renovables</a></li>',
'  <li> <a href="../arduino/index.html" >arduino</a></li>',
'  <li> <a href="">varios</a>',
'      <ul>',
'        <li> <a href="../webenlaces/enlaces.html">Enlaces</a></li>',
'         <li> <a href="../arduino/index.html">Arduino</a></li>',
'         <li> <a href="https://cifpmedinadelcampo.es/iea/" >CIFP Electricidad</a></li>',
'         <li> <a href="../webenlaces/enlaces.html">enlaces</a></li>',

'      </ul> ',
'  </li>',
'</ul>');